[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
    -D__FREERTOS=1
lib_deps =
    https://github.com/johnrickman/LiquidCrystal_I2C.git
    https://github.com/gin66/FastAccelStepper.git
monitor_speed = 115200
