[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_deps =
    https://github.com/johnrickman/LiquidCrystal_I2C.git
    teemuatlut/TMCStepper@^0.7.3
monitor_speed = 115200
