#pragma once

#define I2C_SDA_PIN 0
#define I2C_SCL_PIN 1
#define STEP_PIN 2
#define DIR_PIN 3
#define ENC_A_PIN 6
#define ENC_B_PIN 7
#define ENC_BTN_PIN 8
#define A3144_PIN 9
#define EN_PIN 10
#define HALL_ADC_PIN 26

#define LCD_I2C_ADDRESS 0x27
#define LCD_COLS 20
#define LCD_ROWS 4

#define MICROSTEP 8
#define STEPS_PER_REV (200 * MICROSTEP)
#define COUNT_STEPS_PER_REV STEPS_PER_REV
#define DIR_CW_LEVEL HIGH

#define MIN_RPM 1
#define MAX_RPM 1500

// Rampa reczna: +10 RPM co MOTOR_RPM_RAMP_INTERVAL_MS (bez ciaglego FAS linear ramp).
#define MOTOR_RPM_RAMP_STEP 10
#define MOTOR_RPM_RAMP_INTERVAL_MS 350
#define MOTOR_RPM_RAMP_START 10
// Przyspieszenie miedzy kolejnymi progami 10 RPM (kroki/s^2).
#define MOTOR_ACCEL_STEPS_S2 2200
#define MOTOR_DIR_SETUP_US 8

#define USE_TMC2209_UART 0
#define TMC_UART_TX_PIN 4
#define TMC_UART_RX_PIN 5
#define TMC_UART_BAUD 115200
#define TMC_UART_READ_TIMEOUT_MS 2
#define TMC_DRIVER_ADDRESS 0b00
#define TMC_R_SENSE 0.11f
#define TMC_VERSION_OK 0x21

#define A3144_PULSES_PER_REV 1
#define A3144_COUNT_ON_FALLING 1
#define A3144_PERIOD_US(rpm) (60000000UL / (uint32_t)(rpm))
#define A3144_DEBOUNCE_US 800
#define A3144_MIN_INTERVAL_US ((A3144_PERIOD_US(MAX_RPM) * 45UL) / 100UL)

#define USE_GAUSS_MONITOR 0

#define MAX_PRESETS 32
#define MAX_TURNS 99999L
#define TURN_DIGITS 5
#define RPM_DIGITS 4
#define PRESET_NAME_LEN 12
#define EEPROM_SIZE 1024
#define LONG_PRESS_MS 800
#define BLINK_MS 500
#define WINDING_UI_INTERVAL_MS 750
#define ENCODER_DETENTS_PER_REV 20
#define PREWIND_STEP_INTERVAL_US 800
